# This is a basic workflow to help you get started with Actions

name: Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'ssprove.opam'
      - '.github/workflows/image.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  TEST_TAG: nsidorenco/ssprove:test
  MATHCOMP_VERSION: 1.13.0
  COQ_VERSION: 8.14

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
       opam_file: 'ssprove.opam'
       custom_image: ${{ env.MATHCOMP_VERSION }}-coq-${{ env.COQ_VERSION }}
       before_script: |
        startGroup "Workaround permission issue"
          sudo chown -R coq:coq .  # <--
        endGroup
       script: |
        startGroup "Build"
          opam exec -- make -j4
        endGroup
    - name: Revert permissions
      # to avoid a warning at cleanup time
      if: ${{ always() }}
      run: sudo chown -R 1001:116 .  # <--
      
  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            MATHCOMP_VERSION=${{ env.MATHCOMP_VERSION }}
            COQ_VERSION=${{ env.COQ_VERSION }}
          push: true
          tags: nsidorenco/ssprove:latest
