# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - mathcomp/mathcomp:1.13.0-coq-8.14
      max-parallel: 4
      fail-fast: false  # don't stop jobs if one fails
    steps:
    - name: Try to restore build cache
      id: cache
      uses: actions/cache@v2
      with:
        path: "~/.opam"
        key: ${{ matrix.image }}-opam-cache-${{github.base_ref}}-${{github.ref}}
        restore-keys: |
          ${{ matrix.image }}-opam-cache--refs/heads/${{github.base_ref}}
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
       opam_file: 'ssprove.opam'
       custom_image: ${{ matrix.image }}
       before_install: |
        startGroup "Restore opam"
          mkdir -p ~/coq/.opam. 
          (cp -r /home/.opam ~/.opam 2>/dev/null || :)
        endGroup
       before_script: |
        startGroup "Workaround permission issue"
          sudo chown -R coq:coq .  # <--
        endGroup
       script: |
        startGroup "Build"
          opam exec -- make -j4
        endGroup
       after_script: |
        startGroup "Move opam cache"
          mkdir -p ~/.opam
          (cp -r ~/.opam /home/.opam || :)
         endGroup
    - name: Revert permissions
      # to avoid a warning at cleanup time
      if: ${{ always() }}
      run: sudo chown -R 1001:116 .  # <--
